events {}
http {
    # 도커 내부의 DNS 서버 주소입니다. (이걸 써야 컨테이너를 하나하나 찾습니다.)
    resolver 127.0.0.11 valid=1s;
    
    upstream my-web-cluster {
        # 'round-robin'이 기본이지만, 강제로 명시해 줄 수 있습니다.
        # 'web-node' 뒤에 붙은 컨테이너들을 하나씩 다 찾아내서 라운드 로빈(순차분배) 합니다.
        zone upstream_dynamic 64k;
        server web-node:3000; # 포트 번호 수정
    }

    server {
        listen 80;
        location / {
            proxy_pass http://my-web-cluster;

            # [중요] Keep-Alive를 끄고 매번 다른 서버로 보내게 유도
            proxy_set_header Connection "";
            keepalive_timeout 0;

            # 브라우저에게 캐시하지 말라고 강력히 권고
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        }
    }
}